namespace MQR.DataAccess.Entities;

/// <summary>
/// Represents a distributed lock over a mainframe session.
/// We take this lock because otherwise we have no way of correlating our input to the mainframe
/// with the mainframe's eventual output. This lets us exclude a session from taking on any further work
/// until we have received a response from the mainframe.
/// Thus we always know a given response is for the latest request.
/// </summary>
public class ActiveSession
{
    /// <summary>
    /// The session id for the vdu session, generated by the mainframe.
    /// </summary>
    public required string SessionId { get; set; }
    
    /// <summary>
    /// The session name for the print session, generated by the mainframe.
    /// </summary>
    public required string TopsAlternateName { get; set; }

    /// <summary>
    /// When a lock for this session was last rented out.
    /// </summary>
    public DateTime? LockTakenUtc { get; set; }
    
    public Guid? RequestId { get; set; }

    /// <summary>
    /// Identifier for the HTTP-level request.
    /// </summary>
    public RequestSession? RequestSession { get; set; }
}